"""Initial Migration

Revision ID: 02e5f02140f2
Revises: 
Create Date: 2024-08-19 20:33:11.060903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02e5f02140f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('lawyer_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('court_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['lawyer_id'], ['lawyers.user_id'], name=op.f('fk_cases_lawyer_id_lawyers')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_cases_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cases'))
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('lawyer_id', sa.Integer(), nullable=True),
    sa.Column('review', sa.String(length=1000), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lawyer_id'], ['lawyers.user_id'], name=op.f('fk_reviews_lawyer_id_lawyers')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reviews_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews'))
    )
    op.create_table('histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.String(length=1000), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_histories_case_id_cases')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_histories_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_histories'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('histories')
    op.drop_table('reviews')
    op.drop_table('cases')
    # ### end Alembic commands ###
