"""Add reply_to column to Message model

Revision ID: 15e47dc8cdc8
Revises: 73f8aa91052a
Create Date: 2024-08-14 20:18:28.531159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15e47dc8cdc8'
down_revision = '73f8aa91052a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reply_to', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_messages_reply_to_messages'), 'messages', ['reply_to'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_messages_reply_to_messages'), type_='foreignkey')
        batch_op.drop_column('reply_to')

    # ### end Alembic commands ###
